version: "3"
services:
  ui:
    container_name: dgl_ui
    image: node:19
    volumes:
      - ./ui/:/opt/sca/app
      - dgl_ui_modules:/opt/sca/app/node_modules
    working_dir: /opt/sca/app
    command: sh -c "npm install && npm run builddev"
    

  api:
    container_name: dgl_api
    build:
      context: ./api
      args:
        APP_UID: ${APP_UID} # read from .env file
        APP_GID: ${APP_GID} # read from .env file
    volumes:
      - ./api/:/opt/sca/app
      - dgl_api_modules:/opt/sca/app/node_modules
    expose:
      - 3030
    # entrypoint: [ "tail", "-f", "/dev/null" ]
    networks:
      dgl_network:
        ipv4_address: 172.19.0.2

  worker_api:
    container_name: dgl_worker_api
    build:
      context: ./worker/
      args:
        APP_UID: ${APP_UID} # read from .env file
        APP_GID: ${APP_GID} # read from .env file
    volumes:
      - ./worker/scaworkers/:/opt/sca/app/scaworkers
      - ./worker/.env:/opt/sca/app/.env
    expose:
      - 5001
    environment:
      - PORT=5001
    restart: on-failure
    networks:
      dgl_network:
        ipv4_address: 172.19.0.3

volumes:
  dgl_ui_modules:
    external: false

  dgl_api_modules:
    external: false

networks:
  dgl_network:
    ipam:
      config:
        - subnet: 172.19.0.0/24