version: "3"
name: bioloop
services:
  ui:
    restart: unless-stopped
    image: node:19
    volumes:
      - ./ui/:/opt/sca/app
      - ui_modules:/opt/sca/app/node_modules
    working_dir: /opt/sca/app
    command: sh -c "npm install && npm run builddev"
    

  api:
    restart: unless-stopped
    build:
      context: ./api
      args:
        APP_UID: ${APP_UID} # read from .env file
        APP_GID: ${APP_GID} # read from .env file
    volumes:
      - ./api/:/opt/sca/app
      - api_modules:/opt/sca/app/node_modules
    expose:
      - 3030
    # entrypoint: [ "tail", "-f", "/dev/null" ]
    depends_on:
     - postgres
    networks:
      network:
        ipv4_address: 172.19.0.2

  postgres:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/prod/db_postgres:/var/lib/postgresql/data
      - ./db/postgres/scripts:/docker-entrypoint-initdb.d
    expose:
      - 5432
    networks:
      network:
        ipv4_address: 172.19.0.3

volumes:
  ui_modules:
    external: false

  api_modules:
    external: false

networks:
  network:
    ipam:
      config:
        - subnet: 172.19.0.0/24