version: "3"
name: cpa
services:
  ui:
    container_name: ui
    image: node:19
    volumes:
      - ./ui/:/opt/sca/app
      - ui_modules:/opt/sca/app/node_modules
    working_dir: /opt/sca/app
    command: sh -c "npm install && npm run builddev"
    

  api:
    container_name: api
    build:
      context: ./api
      args:
        APP_UID: ${APP_UID} # read from .env file
        APP_GID: ${APP_GID} # read from .env file
    volumes:
      - ./api/:/opt/sca/app
      - api_modules:/opt/sca/app/node_modules
    expose:
      - 3030
    # entrypoint: [ "tail", "-f", "/dev/null" ]
    networks:
      network:
        ipv4_address: 172.19.0.2

volumes:
  ui_modules:
    external: false

  api_modules:
    external: false

networks:
  network:
    ipam:
      config:
        - subnet: 172.19.0.0/24