-- CreateEnum
CREATE TYPE "ALERT_STATUS" AS ENUM ('SCHEDULED', 'ACTIVE', 'EXPIRED');

-- AlterTable
ALTER TABLE "alert" ADD COLUMN     "is_hidden" BOOLEAN DEFAULT false,
ADD COLUMN     "status" "ALERT_STATUS" NOT NULL DEFAULT 'SCHEDULED',
ALTER COLUMN "label" DROP NOT NULL,
ALTER COLUMN "start_time" DROP NOT NULL,
ALTER COLUMN "start_time" DROP DEFAULT;
