-- Duplicate Detection Redesign Migration
--
-- Changes:
--   1. Remove version column from dataset and update unique constraint
--   2. Remove dataset_action_item table and its enums
--   3. Add comparison_process_id, comparison_status, metadata to dataset_duplication
--   4. Add DATASET_DUPLICATION_ANALYSIS_STATUS enum
--   5. Replace DATASET_INGESTION_CHECK_TYPE enum values with new ones
--   6. Add source_dataset_id to dataset_ingestion_file_check
--   7. Add md5 index to dataset_file
--   8. Remove dataset_action_items relation from notification (table drop handles this)

-- Step 1: Drop dataset_action_item (removes action_items FK on dataset and notification)
DROP TABLE IF EXISTS "dataset_action_item";
DROP TYPE IF EXISTS "DATASET_ACTION_ITEM_TYPE";
DROP TYPE IF EXISTS "DATASET_ACTION_ITEM_STATUS";

-- Step 2: Remove version column from dataset
ALTER TABLE "dataset" DROP COLUMN IF EXISTS "version";

-- Step 3: Drop the old 5-column unique constraint, add the 3-column one from origin/main
--         The constraint name is auto-generated by Prisma based on column list.
ALTER TABLE "dataset" DROP CONSTRAINT IF EXISTS "dataset_name_type_is_deleted_is_duplicate_version_key";
ALTER TABLE "dataset" DROP CONSTRAINT IF EXISTS "dataset_name_type_is_deleted_key";
ALTER TABLE "dataset" ADD CONSTRAINT "dataset_name_type_is_deleted_key" UNIQUE ("name", "type", "is_deleted");

-- Step 4: DATASET_DUPLICATION_ANALYSIS_STATUS enum (renamed from COMPARISON_STATUS)
DO $$ BEGIN
  ALTER TYPE "COMPARISON_STATUS" RENAME TO "DATASET_DUPLICATION_ANALYSIS_STATUS";
EXCEPTION
  WHEN undefined_object THEN null;
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "DATASET_DUPLICATION_ANALYSIS_STATUS" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'NOT_DUPLICATE', 'FAILED');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Step 5: Add new columns to dataset_duplication
ALTER TABLE "dataset_duplication"
  ADD COLUMN IF NOT EXISTS "comparison_process_id" TEXT,
  ADD COLUMN IF NOT EXISTS "comparison_status" "DATASET_DUPLICATION_ANALYSIS_STATUS" NOT NULL DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS "metadata" JSONB;

-- Step 6: Replace DATASET_INGESTION_CHECK_TYPE enum values.
--         PostgreSQL cannot drop enum values; we must recreate the type.
--         First clear any existing data that used old enum values.
DELETE FROM "dataset_ingestion_file_check";
DELETE FROM "dataset_ingestion_check";

ALTER TABLE "dataset_ingestion_check" ALTER COLUMN "type" TYPE TEXT;
DROP TYPE IF EXISTS "DATASET_INGESTION_CHECK_TYPE";
CREATE TYPE "DATASET_INGESTION_CHECK_TYPE" AS ENUM (
  'EXACT_CONTENT_MATCHES',
  'SAME_PATH_SAME_CONTENT',
  'SAME_PATH_DIFFERENT_CONTENT',
  'SAME_CONTENT_DIFFERENT_PATH',
  'ONLY_IN_INCOMING',
  'ONLY_IN_ORIGINAL'
);
ALTER TABLE "dataset_ingestion_check"
  ALTER COLUMN "type" TYPE "DATASET_INGESTION_CHECK_TYPE"
  USING "type"::"DATASET_INGESTION_CHECK_TYPE";

-- Step 7: Add source_dataset_id to dataset_ingestion_file_check
ALTER TABLE "dataset_ingestion_file_check"
  ADD COLUMN IF NOT EXISTS "source_dataset_id" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "dataset_ingestion_file_check" ALTER COLUMN "source_dataset_id" DROP DEFAULT;

-- Step 8: Add md5 index to dataset_file
CREATE INDEX IF NOT EXISTS "dataset_file_md5_idx" ON "dataset_file" ("md5");
