import json
from pathlib import Path
import fire
import shutil
import os
import hashlib
from typing import List, Tuple, Dict, Optional
import time
import traceback
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
            
from sca_rhythm import Workflow

import workers.workflow_utils as wf_utils
from workers.celery_app import app as celery_app
import workers.api as api
from workers.config import common
from workers.utils import checksum
    

class Registration:
    def __init__(self,
                 dataset_type: str,
                 path: str,
                 project_id: str = None,
                 description: str = None,
                 prefix: str = None,
                 suffix: str = None,
                 ingest_subdirs: bool = False,
                 skip_checksum_verification: bool = False):
        self.dataset_type = dataset_type
        self.path = path
        self.description = description
        self.project_id = project_id
        self.prefix = prefix
        self.suffix = suffix
        self.ingest_subdirs = ingest_subdirs
        self.skip_checksum_verification = skip_checksum_verification
        self.project = None
        self.renamed_hard_links_parent_dir = None

        if self.project_id:
            self.project = api.get_project(project_id=self.project_id)


    def should_process_candidate(self, candidate_name: str) -> bool:
        """
        Check if a candidate should be processed (idempotence check).
        Returns True if the candidate needs processing, False if already done.
        """
        # If already registered, skip
        if self.is_dataset_registered(dataset_name=candidate_name):
            print(f"Candidate {candidate_name} is already registered, skipping...")
            return False
        
        # If currently registering, skip (let it finish)
        if self.is_dataset_registering(dataset_name=candidate_name):
            print(f"Candidate {candidate_name} is currently being registered, skipping...")
            return False
        
        return True


    def prepare_candidate_hard_link(self, original_path: Path, candidate_new_name: str) -> Optional[Path]:
        """
        Prepare a candidate directory for registration using hard links.
        Returns the path to the prepared directory with hard-links.
        This method is only called for candidates that need hard-linking.
        """
            
        new_dir_path = self.renamed_hard_links_parent_dir / candidate_new_name
        
        # If the new directory exists but candidate is not registered/registering, delete and recreating.
        # This is to ensure that hard-links are not corrupted ones generated by a previous run of the script.
        if new_dir_path.exists():
            print(f"New directory {candidate_new_name} exists but is not registered neither currently being registered. Deleting and recreating...")
            shutil.rmtree(path=new_dir_path)
            print(f"Deleted existing directory: {new_dir_path}")
        
        # Create the new directory using hard-links
        print(f"Creating new directory with hard-links: {original_path} -> {new_dir_path}")
        self.create_hard_linked_directory(original_path, new_dir_path)
        print(f"Successfully created with hard-links: {new_dir_path}")
        
        return new_dir_path


    def create_hard_linked_directory(self, src_path: Path, dst_path: Path) -> None:
        """
        Create a hard-link copy of a directory structure.
        """
        # Create the destination directory
        dst_path.mkdir(parents=True, exist_ok=True)
        
        # Walk through the source directory and create hard-links
        for root, dirs, files in os.walk(src_path):
            # Calculate the relative path from source
            rel_path = Path(root).relative_to(src_path)
            dst_root = dst_path / rel_path
            
            # Create subdirectories
            for dir_name in dirs:
                (dst_root / dir_name).mkdir(exist_ok=True)
            
            # Create hard-links for files
            for file_name in files:
                src_file = Path(root) / file_name
                dst_file = dst_root / file_name
                
                try:
                    # Remove existing hard-link if it exists, then create new one
                    # This is to ensure that hard-links are not corrupted ones generated by a previous run of the script.
                    if dst_file.exists():
                        dst_file.unlink()
                    # Create hard-link
                    os.link(src_file, dst_file)
                except OSError as e:
                    # If hard-link fails, fail the entire script
                    print(f"❌ Hard-link failed for {src_file}: {e}")
                    print(f"💥 Script will fail early due to hard-link creation error.")
                    raise RuntimeError(f"Hard-link operation failed: {e}")


    def verify_hard_links(self, src_path: Path, dst_path: Path) -> bool:
        """
        Verify that hard-linked directories have identical content using directory checksums.
        
        Args:
            src_path: Source directory path
            dst_path: Destination directory path (hard-linked copy)
            
        Returns:
            bool: True if directories are identical, False otherwise
        """
        try:
            print(f"Verifying hard-links between {src_path} and {dst_path}...")
            
            # Check if directories exist
            if not src_path.exists() or not dst_path.exists():
                print(f"❌ One or both directories don't exist")
                return False
            
            # Direct directory checksum comparison without using directories_are_equal
            if self.directories_checksum_equal(src_path, dst_path):
                print(f"✅ Directory checksum verification passed: {src_path} == {dst_path}")
                return True
            else:
                print(f"❌ Directory checksum verification failed: {src_path} != {dst_path}")
                return False
                
        except Exception as e:
            print(f"Error during hard-link verification: {e}")
            return False


    def calculate_directory_checksum(self, dir_path: Path) -> str:
        """
        Calculate a single checksum for an entire directory by combining all file checksums.
        This traverses files but gives accurate directory-level verification.
        
        Args:
            dir_path: Directory path to calculate checksum for
            
        Returns:
            str: MD5 checksum of the entire directory
        """
        try:
            checksums = []
            
            # Walk through all files in the directory
            for root, dirs, files in os.walk(dir_path):
                # Sort for consistent ordering
                for file in sorted(files):
                    file_path = Path(root) / file
                    if file_path.is_file():
                        from workers.utils import checksum
                        file_hash = checksum(str(file_path), block_size=65536)
                        checksums.append(f"{file_path.relative_to(dir_path)}:{file_hash}")
            
            # Sort checksums for consistent ordering
            checksums.sort()
            
            # Combine all checksums into one string and hash it
            combined = "|".join(checksums)
            return hashlib.md5(combined.encode()).hexdigest()
            
        except Exception as e:
            print(f"Error calculating directory checksum: {e}")
            return ""


    def directories_checksum_equal(self, dir1: Path, dir2: Path) -> bool:
        """
        Compare two directories by calculating and comparing their overall directory checksums.
        This always compares entire directory checksums, never individual files.
        
        Args:
            dir1: First directory path
            dir2: Second directory path
            
        Returns:
            bool: True if directories have identical checksums, False otherwise
        """
        try:
            # Calculate checksums for both directories
            checksum1 = self.calculate_directory_checksum(dir1)
            checksum2 = self.calculate_directory_checksum(dir2)
            
            if not checksum1 or not checksum2:
                print(f"❌ Failed to calculate checksums: dir1={checksum1}, dir2={checksum2}")
                return False
            
            # Compare the directory checksums
            are_equal = checksum1 == checksum2
            
            if are_equal:
                print(f"✅ Directory checksums match: {checksum1[:8]}... == {checksum2[:8]}...")
            else:
                print(f"❌ Directory checksums differ: {checksum1[:8]}... != {checksum2[:8]}...")
            
            return are_equal
            
        except Exception as e:
            print(f"Error during directory checksum comparison: {e}")
            return False


    def verify_hard_links_parallel(self, verification_tasks: List[Tuple[Path, Path, str]]) -> bool:
        """
        Verify multiple hard-linked directories in parallel using directory-level checksums.
        
        Args:
            verification_tasks: List of tuples containing (src_path, dst_path, candidate_name)
            
        Returns:
            bool: True if all verifications pass, False if any fail
        """
        try:
            print(f"Starting parallel verification of {len(verification_tasks)} directories...")
            
            # Use ThreadPoolExecutor for parallel verification with configurable limits
            default_workers = common.config['registration']['register_ondemand']['default_workers']
            max_allowed_workers = common.config['registration']['register_ondemand']['max_workers']
            
            # Calculate workers with upper limit enforcement
            calculated_workers = min(len(verification_tasks), default_workers)
            max_workers = min(calculated_workers, max_allowed_workers)
            
            print(f"📊 Worker Configuration: {len(verification_tasks)} tasks, {default_workers} default, {max_allowed_workers} max allowed → Using {max_workers} workers")
            
            verification_results = {}
            failed_verifications = []
            
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                # Submit all verification tasks
                future_to_task = {
                    executor.submit(self.verify_hard_links, src_path, dst_path): (src_path, dst_path, candidate_name)
                    for src_path, dst_path, candidate_name in verification_tasks
                }
                
                # Collect results as they complete
                for future in as_completed(future_to_task):
                    src_path, dst_path, candidate_name = future_to_task[future]
                    try:
                        result = future.result()
                        verification_results[candidate_name] = result
                        
                        if result:
                            print(f"✅ Parallel verification completed for: {candidate_name}")
                        else:
                            print(f"❌ Parallel verification failed for: {candidate_name}")
                            failed_verifications.append(candidate_name)
                            
                    except Exception as e:
                        print(f"❌ Exception during parallel verification of {candidate_name}: {e}")
                        failed_verifications.append(candidate_name)
                        verification_results[candidate_name] = False
            
            # Summary of results
            successful_count = sum(1 for result in verification_results.values() if result)
            total_count = len(verification_results)
            
            print(f"\n📊 Parallel Verification Summary:")
            print(f"   Total directories: {total_count}")
            print(f"   Successful: {successful_count}")
            print(f"   Failed: {len(failed_verifications)}")
            
            if failed_verifications:
                print(f"   Failed directories: {', '.join(failed_verifications)}")
                return False
            else:
                print(f"   ✅ All {total_count} directories verified successfully!")
                return True
                
        except Exception as e:
            print(f"Error during parallel verification: {e}")
            return False


    def get_eligible_candidates(self, dir_path: str) -> List[Tuple[str, Path]]:
        """
        Get list of eligible candidates to register based on ingest mode.
        
        Returns:
            List of tuples containing (dataset_name, original_path)
        """
        directory_path: Path = Path(dir_path)
        directory_name: str = directory_path.name
        
        if not self.ingest_subdirs:
            # Return parent directory as single candidate
            parent_dir_new_name = generate_dataset_new_name(
                prefix=self.prefix,
                suffix=self.suffix,
                dataset_name=directory_name,
            )
            return [(parent_dir_new_name, directory_path)]
        else:
            # Return subdirectories as candidates (only subdirectories at first level are considered)
            candidates = []
            non_directory_files = []

            for item in directory_path.iterdir():
                if not item.is_dir():
                    non_directory_files.append(item.name)
                    continue
                subdirectory_new_name: str = generate_dataset_new_name(
                    prefix=self.prefix,
                    suffix=self.suffix,
                    dataset_name=item.name,
                )
                print(f"Found candidate: {item.name} -> {subdirectory_new_name}")
                candidates.append((subdirectory_new_name, item))
            
            # Log non-directory files that won't be registered
            if non_directory_files:
                print(f"⚠️  Non-directory files found (will not be registered as datasets): {', '.join(non_directory_files)}")

            return candidates


    def process_and_register_candidates(self,
                                      candidates: List[Tuple[str, Path]], 
                                      dir_path: str,
                                      description: str = None,
                                      dry_run: bool = False) -> None:
        """
        Process and register a list of datasets sequentially.
        
        Args:
            candidates: List of tuples containing (dataset_name, original_path)
            dir_path: Original directory path for cleanup purposes
            description: Optional description for datasets
            dry_run: Whether to simulate the process without making changes
        """
        
        # Filter candidates that need processing
        candidates_to_process = []
        for candidate_name, original_path in candidates:
            if self.should_process_candidate(candidate_name):
                candidates_to_process.append((candidate_name, original_path))            
        if not candidates_to_process:
            print("No candidates need processing - all are already registered or being processed.")
            return

        print(f"Processing {len(candidates_to_process)} candidates...")

        # Prepare candidates (create hard-links if needed, use original paths otherwise)
        prepared_candidates = self.prepare_candidates(candidates_to_process, dir_path)
        if not prepared_candidates:
            print("No prepared candidates found. Early return: nothing to verify or register.")
            return
            
        # Verify hard-links integrity
        verification_tasks = self.verify_hard_links_checksums(prepared_candidates)
        if verification_tasks is None:  # Verification failed
            return
            
        # Register datasets
        self.register_candidate_dirs(prepared_candidates, description, dry_run)
        
        # Summarize results and cleanup
        self.cleanup(prepared_candidates, verification_tasks, dry_run)


    def prepare_candidates(self, candidates_to_process: List[Tuple[str, Path]], 
                                     dir_path: str) -> List[Tuple[str, Path, Path]]:
        print(f"ℹ️ Preparing {len(candidates_to_process)} candidates for registration...")
        
        # Determine if hard-linking is needed and prepare directory only if necessary
        need_hard_link_creation = any(
            candidate_name != original_path.name
            for candidate_name, original_path in candidates_to_process
        )
        
        if need_hard_link_creation:
            directory_path = Path(dir_path)
            self.renamed_hard_links_parent_dir = directory_path.parent / f".{directory_path.name}__renamed"
            self.renamed_hard_links_parent_dir.mkdir(exist_ok=True)
            print(f"Created hidden directory which will contain hard-links: {self.renamed_hard_links_parent_dir}")            
            # Log which candidates require hard-linking
            hard_link_candidates = [(name, path) for name, path in candidates_to_process if name != path.name]
            print(f"Found {len(hard_link_candidates)} candidates requiring hard-linking")
        else:
            self.renamed_hard_links_parent_dir = None
            print(f"No hard-linking needed. All candidates will use original paths.")
        
        prepared_candidates = []
        
        hard_link_candidates = [(name, path) for name, path in candidates_to_process if name != path.name]
        original_path_candidates = [(name, path) for name, path in candidates_to_process if name == path.name]
        
        # Process candidates that need hard-linking
        for candidate in hard_link_candidates:
            candidate_name, original_path = candidate
            try:
                # Prepare hard-link
                prepared_path = self.prepare_candidate_hard_link(original_path, candidate_name)
                if prepared_path:
                    prepared_candidates.append((candidate_name, prepared_path, original_path))
                    print(f"✅ Prepared hard-link for: {candidate_name}")
                else:
                    print(f"⚠️ Skipped hard-link preparation for: {candidate_name}")
                    
            except Exception as e:
                print(f"❌ Error preparing hard-link for {candidate_name}: {e}")
                traceback.print_exc()
        
        # Add candidates that don't need hard-linking (use original paths directly)
        for candidate in original_path_candidates:
            candidate_name, original_path = candidate
            prepared_candidates.append((candidate_name, original_path, original_path))
            print(f"ℹ️ Using original path for: {candidate_name} (no renaming needed)")

        print(f"Prepared {len(prepared_candidates)} candidates for registration")
        return prepared_candidates


    def verify_hard_links_checksums(self, prepared_candidates: List[Tuple[str, Path, Path]]) -> Optional[List[Tuple[Path, Path, str]]]:
        """Verify all data-integrity of created hard-links before registration"""
        if self.skip_checksum_verification:
            print(f"\n⚠️ Skipping checksum verification (disabled by user)")
            print("⚠️  WARNING: Data integrity cannot be guaranteed without verification!")
            return []
            
        print(f"\n🔍 Verifying {len(prepared_candidates)} hard-links...")
        verification_tasks = []
        
        for candidate_name, prepared_path, original_path in prepared_candidates:
            if prepared_path != original_path:  # Only verify if hard-linking was used
                verification_tasks.append((original_path, prepared_path, candidate_name))
        
        if verification_tasks:
            verification_success = self.verify_hard_links_parallel(verification_tasks)
            if not verification_success:
                print("❌ Hard-link verification failed. Cleaning up and aborting...")
                # Clean up hard-linked directories on verification failure
                if self.renamed_hard_links_parent_dir and self.renamed_hard_links_parent_dir.exists():
                    shutil.rmtree(self.renamed_hard_links_parent_dir)
                    print(f"Cleaned up hard-linked directories in {self.renamed_hard_links_parent_dir}")
                return None
            print("✅ All hard-links verified successfully!")
        else:
            print("ℹ️  No hard-links to verify - using original paths directly")
            
        return verification_tasks


    def register_candidate_dirs(self, hard_link_preparations: List[Tuple[str, Path, Path]], 
                                   description: str, dry_run: bool) -> None:
        """Phase 3: Register all datasets (using bulk endpoint if multiple)"""
        if dry_run:
            print(f"\n📝 Phase 3: DRY RUN - Would register {len(hard_link_preparations)} datasets")
            print("   (No actual API calls made in dry run mode)")
            
            # Log what would be registered
            for candidate_name, prepared_path, original_path in hard_link_preparations:
                if prepared_path != original_path:
                    print(f"   📁 Directory '{original_path.name}' would be registered as dataset '{candidate_name}'")
                else:
                    print(f"   📁 Directory '{original_path.name}' would be registered as dataset '{candidate_name}' (no renaming)")
        else:
            print(f"\n📝 Phase 3: Registering {len(hard_link_preparations)} datasets...")
            
            if len(hard_link_preparations) > 1:
                # Use bulk endpoint for multiple datasets
                print(f"📦 Using bulk registration endpoint for {len(hard_link_preparations)} datasets")
                success = self.register_datasets_bulk(hard_link_preparations, description)
                if success:
                    print(f"✅ Bulk registration successful for all {len(hard_link_preparations)} datasets")
                else:
                    print(f"❌ Bulk registration failed")
                    return
            else:
                # Single dataset registration
                candidate_name, prepared_path, original_path = hard_link_preparations[0]
                try:
                    self.register_single_dataset(candidate_name, prepared_path, description)
                    print(f"✅ Single registration successful: {candidate_name}")
                except Exception as e:
                    print(f"❌ Single registration failed for {candidate_name}: {e}")
                    return


    def cleanup(self, hard_link_preparations: List[Tuple[str, Path, Path]], 
                                   verification_tasks: List[Tuple[Path, Path, str]], 
                                   dry_run: bool) -> None:
        """Final summary and cleanup operations"""
        if dry_run:
            print(f"\n🎉 DRY RUN completed successfully!")
            print(f"   Would prepare: {len(hard_link_preparations)}")
            print(f"   Would verify: {len(verification_tasks)}")
            print(f"   Would register: {len(hard_link_preparations)}")
            print(f"   No actual changes made")
        else:
            print(f"\n🎉 All phases completed successfully!")
            print(f"   Prepared: {len(hard_link_preparations)}")
            print(f"   Verified: {len(verification_tasks)}")
            print(f"   Registered: {len(hard_link_preparations)}")

        # Clean up renamed directories
        if self.renamed_hard_links_parent_dir and self.renamed_hard_links_parent_dir.exists() and self.ingest_subdirs:
            if dry_run:
                print(f"\n🧹 DRY RUN: Cleaning up test hard-links from {self.renamed_hard_links_parent_dir}")
                print("   (Hard-links were created for testing - cleaning them up now)")
                shutil.rmtree(path=self.renamed_hard_links_parent_dir)
                print(f"🧹 Cleaned up test hard-links: {self.renamed_hard_links_parent_dir}")
            else:
                print(f"\n🧹 Checking if cleanup is safe for {self.renamed_hard_links_parent_dir}...")
                
                # Check if all datasets are in ARCHIVE state
                all_archived = True
                for candidate_name, prepared_path, original_path in hard_link_preparations:
                    if not self.is_dataset_registered(dataset_name=candidate_name):
                        all_archived = False
                        print(f"⚠️  Dataset {candidate_name} not yet archived - skipping cleanup")
                        break
                
                if all_archived:
                    print("✅ All datasets archived - safe to clean up hard-linked directories")
                    shutil.rmtree(path=self.renamed_hard_links_parent_dir)
                    print(f"🧹 Cleaned up renamed directory: {self.renamed_hard_links_parent_dir}")
                else:
                    print("⏳ Some datasets not yet archived - leaving hard-linked directories for now")
                    print(f"   Renamed directory preserved at: {self.renamed_hard_links_parent_dir}")
                    print(f"   Cleanup will happen automatically when all datasets reach ARCHIVE state")


    def register_datasets(self,
                         dir_path: str,
                         description: str = None,
                         dry_run: bool = False) -> None:
        """
        Idempotent method - will not register a duplicate Dataset.

        :param dir_path:
        :param description:
        :param dry_run:
        :return:
        """
        directory_path: Path = Path(dir_path)
        directory_name: str = directory_path.name
        print(f"Processing {str(directory_name)}")

        # Get eligible candidates based on ingest mode
        candidates = self.get_eligible_candidates(dir_path)

        # Process eligible candidates
        self.process_and_register_candidates(candidates, dir_path, description, dry_run)

    
    def register_single_dataset(self, dataset_name: str, dataset_path: Path, description: str = None) -> None:
        """
        Register a single dataset as either Raw Data or Data Product based on dataset_type.
        
        :param dataset_name: Name of the dataset to register
        :param dataset_path: Path to the dataset directory
        :param description: Optional description for the dataset
        """
        print(f'registering {self.dataset_type} {dataset_name}')
        
        try:            
            # Get workflow body for 'integrated' workflow
            wf_body = wf_utils.get_wf_body(wf_name='integrated')
            
            # Create workflow object
            wf = Workflow(celery_app=celery_app, **wf_body)
            
            # Prepare dataset payload
            dataset_payload = {
                'name': dataset_name,
                'type': self.dataset_type,
                'workflow_id': wf.workflow['_id'],
                'origin_path': str(dataset_path),
                **({'project_id': self.project_id} if self.project_id else {}),
                **({'description': description} if description else {})
            }
            
            # Create dataset via API
            created_dataset = api.create_dataset(dataset_payload)
            
            # Start the workflow
            wf.start(created_dataset['id'])
            
            print(f"✅ Successfully registered and started workflow for: {dataset_name}")
            
        except api.DatasetAlreadyExistsError:
            print(f'{dataset_name} already exists')
            return
        except Exception as e:
            print(f"❌ Error registering dataset {dataset_name}: {e}")
            raise


    def register_datasets_bulk(self, hard_link_preparations: List[Tuple[str, Path, Path]], description: str = None) -> bool:
        """
        Register multiple datasets using the bulk endpoint.
        
        Args:
            hard_link_preparations: List of (dataset_name, prepared_path, original_path) tuples
            description: Optional description for datasets
            
        Returns:
            bool: True if bulk registration successful, False otherwise
        """
        try:
            print(f"📦 Preparing bulk registration for {len(hard_link_preparations)} datasets...")
            
            # Prepare bulk registration data according to API specification
            bulk_data = []
            for dataset_name, prepared_path, original_path in hard_link_preparations:
                dataset_info = {
                    'name': dataset_name,
                    'type': self.dataset_type,
                    'origin_path': str(prepared_path)
                }
                # Add description if provided
                if description:
                    dataset_info['metadata'] = {'description': description}
                
                bulk_data.append(dataset_info)
            
            # Call bulk registration endpoint
            print(f"🚀 Calling bulk registration endpoint...")
            from workers.api import bulk_create_datasets
            
            response = bulk_create_datasets(bulk_data)
            
            # Process response
            created_count = len(response.get('created', []))
            conflicted_count = len(response.get('conflicted', []))
            errored_count = len(response.get('errored', []))
            
            print(f"📊 Bulk registration results:")
            print(f"   ✅ Created: {created_count}")
            print(f"   ⚠️  Conflicted: {conflicted_count}")
            print(f"   ❌ Errored: {errored_count}")
            
            # Start workflows for successfully created datasets
            if created_count > 0:
                print(f"🔄 Starting workflows for {created_count} created datasets...")
                for created_dataset in response['created']:
                    try:
                        # Use the dataset ID from the bulk response directly
                        wf_body = wf_utils.get_wf_body(wf_name='integrated')
                        wf = Workflow(celery_app=celery_app, **wf_body)
                        wf.start(created_dataset['id'])
                        print(f"✅ Started workflow for: {created_dataset['name']} (ID: {created_dataset['id']})")
                    except Exception as e:
                        print(f"❌ Failed to start workflow for {created_dataset['name']}: {e}")
            
            # Log conflicts and errors
            if conflicted_count > 0:
                print(f"⚠️  Conflicted datasets (already exist): {[d['name'] for d in response['conflicted']]}")
            
            if errored_count > 0:
                print(f"❌ Failed datasets: {[d['name'] for d in response['errored']]}")
            
            # Consider successful if all datasets were either created or conflicted (already exist)
            total_processed = created_count + conflicted_count
            return total_processed == len(hard_link_preparations) and errored_count == 0
            
        except Exception as e:
            print(f"❌ Error in bulk registration: {e}")
            return False


    def start_workflow_for_existing_dataset(self, dataset_name: str):
        """
        Start the Integrated workflow on an existing dataset.
        """
        try:
            # Get existing dataset
            existing_dataset = self.get_matching_dataset(dataset_name)
            if not existing_dataset:
                print(f"❌ Dataset {dataset_name} not found")
                return False
            
            # Create and start workflow
            wf_body = wf_utils.get_wf_body(wf_name='integrated')
            wf = Workflow(celery_app=celery_app, **wf_body)
            
            # Start workflow on existing dataset
            wf.start(existing_dataset['id'])
            
            print(f"✅ Successfully started Integrated workflow for existing dataset: {dataset_name}")
            return True
            
        except Exception as e:
            print(f"❌ Error starting workflow for {dataset_name}: {e}")
            return False


    def get_matching_dataset(self, dataset_name: str) -> Dict | None:
        matching_datasets: List[Dict] = api.get_all_datasets(dataset_type=self.dataset_type,
                                                             name=dataset_name,
                                                             include_states=True)
        print(f"Searching for {self.dataset_type} named {dataset_name}...")
        print(f"matching datasets count: {len(matching_datasets)}")
        if len(matching_datasets) == 0:
            print(f"{self.dataset_type} {dataset_name} not found")
            return None
        return matching_datasets[0]


    def is_dataset_registered(self,
                              dataset_name: str) -> bool:
        """
        Dataset is considered registered if it has been successfully archived (i.e. it has reached state ARCHIVED).
        """

        print(f"Checking if {self.dataset_type} {dataset_name} is registered...")
        matching_dataset: Dict = self.get_matching_dataset(dataset_name)
        if not matching_dataset:
            return False

        matching_dataset_is_archived = any(
            state['state'] == 'ARCHIVED' for state in matching_dataset.get('states', []))
        return matching_dataset_is_archived


    def is_dataset_registering(self, dataset_name: str) -> bool:
        """
        Dataset is considered to be in the middle of registration if the `Integrated` workflow has been initiated on the Dataset
        """

        print(f"Checking if {self.dataset_type} {dataset_name} is registering...")
        matching_dataset: Dict = self.get_matching_dataset(dataset_name)
        if not matching_dataset:
            return False

        workflow_query_response = api.get_dataset_workflows(dataset_id=matching_dataset['id'])
        dataset_workflows = workflow_query_response['results']

        is_integrated_workflow_present = any(workflow['name'] == 'integrated' for workflow in dataset_workflows)
        return is_integrated_workflow_present


def generate_dataset_new_name(prefix: str = None,
                              suffix: str = None,
                              dataset_name: str = None) -> str:
    """
    Generate a new name for a Dataset directory based on provided components.

    The order of components in the generated name is:
    {prefix}-{dir_name}-{suffix}

    Args:
        prefix (str, optional): A prefix to be added at the beginning of the name.
        suffix (str, optional): A suffix to be added at the end of the name.
        dataset_name (str, optional): The original name of the directory.

    Returns:
        str: The generated name for the directory.

    Example usage:
        generate_dataset_new_name(prefix="pre", suffix="suf", dir_name="data")
        # Returns: "pre-data-suf"

        generate_dataset_new_name(prefix="pre", dir_name="data")
        # Returns: "pre-data"

        generate_dataset_new_name(dir_name="data")
        # Returns: "data"
    """
    components = []

    if prefix:
        components.append(prefix)
    if dataset_name:
        components.append(dataset_name)
    if suffix:
        components.append(suffix)

    return "-".join(filter(None, components))


def main_register_dataset(dir_path: str,
                    dataset_type: str = 'DATA_PRODUCT',
                    project_id: str = None,
                    description: str = None,
                    prefix: str = None,
                    suffix: str = None,
                    ingest_subdirs: bool = False,
                    dry_run: bool = False,
                    skip_checksum_verification: bool = False) -> None:
    """
    Main function to register datasets with enhanced options.
    
    This script uses hard-linking instead of copying for space efficiency and speed,
    especially important when dealing with large datasets (up to 5TB per directory).
    See the main script docstring below for detailed explanation of hard-linking benefits.
    
    Args:
        dir_path: Path to the directory containing subdirectories to process
        dataset_type: Type of dataset to register ('DATA_PRODUCT' or 'RAW_DATA')
        project_id: Optional project ID to associate with datasets
        description: Optional description for datasets
        prefix: Optional prefix for renamed directories
        suffix: Optional suffix for renamed directories
        ingest_subdirs: Whether to ingest subdirectories instead of the parent directory (default: False)
        dry_run: Whether to simulate the process without making changes (default: False)
        skip_checksum_verification: Whether to skip checksum verification (default: False)
    """
    
    # Log checksum verification status
    if skip_checksum_verification:
        print("⚠️  WARNING: You have opted out of checksum verification.")
        print("   This can have serious consequences:")
        print("   - Data integrity cannot be guaranteed")
        print("   - Corrupted hard-links may not be detected")
        print("   - Datasets may be registered with invalid data")
        print("   - Use this option only if you understand the risks!")
        print()
    
    reg = Registration(
        dataset_type=dataset_type,
        path=dir_path,
        project_id=project_id,
        description=description,
        prefix=prefix,
        suffix=suffix,
        ingest_subdirs=ingest_subdirs,
        skip_checksum_verification=skip_checksum_verification
    )
    
    if dry_run:
        print(f"⚠️ DRY RUN MODE")

    reg.register_datasets(dir_path, description, dry_run)


"""
This script processes subdirectories within a given directory, renames them according to
a specific format, and registers them as data products or raw data.

What it does:
1. Processes all subdirectories within the specified DIR_PATH (or the parent directory itself).
2. Optionally renames directories to the format: {PREFIX}-{DIR_NAME}-{SUFFIX}.
3. Creates hard-linked copies of renamed directories to a new '.{arg_dir_name}__renamed' folder (if renaming).
4. Registers each new directory as a Data Product or Raw Data via the register_ondemand script.
5. Optionally assigns a description to each registered dataset.
6. Optionally assigns a Project ID to each registered dataset.

Why Hard-Linking Instead of Copying:
- **Space Efficiency**: Hard-links create additional directory entries that point to the same inode,
  consuming negligible additional disk space compared to full directory copies.
- **Speed**: Hard-linking is nearly instantaneous, even for multi-terabyte directories, as it only
  creates metadata entries rather than duplicating file content.
- **Data Integrity**: Since hard-links reference the same physical data, there's no risk of
  corruption during the copying process.
- **Idempotency**: The script can safely re-run without creating duplicate data, as hard-links
  are automatically cleaned up and recreated if needed.

Note: When ingesting subdirectories (ingest_subdirs=True), only the first level of subdirectories 
within the provided directory is scanned for registration as datasets. Nested subdirectories are not processed.

Usage:
python -m workers.scripts.register_ondemand [OPTIONS] DIR_PATH

Arguments:
DIR_PATH: The path to the directory containing subdirectories to process.

Options:
--dataset-type: Type of dataset to register ('DATA_PRODUCT' or 'RAW_DATA', default: 'DATA_PRODUCT')
--project-id: Optional ID of the project to associate with the registered datasets.
--description: Optional description to add to each registered dataset.
--prefix: Optional prefix to add to renamed directory names.
--suffix: Optional suffix to add to renamed directory names.
--ingest-subdirs: Whether to ingest subdirectories instead of the parent directory (default: False).
        --dry-run: Whether to simulate the process without making changes (default: False).
        --skip-checksum-verification: Whether to skip checksum verification (default: False).

Example usage:
1. Dry run (simulate without changes):
   python -m workers.scripts.register_ondemand /path/to/data_directory --description="Sample dataset description" --dry-run=True

2. Actually process and register with project ID:
   python -m workers.scripts.register_ondemand /path/to/data_directory --project-id=abc123 --dry-run=False

3. Register as raw data with custom prefix:
   python -m workers.scripts.register_ondemand /path/to/data_directory --dataset-type=RAW_DATA --prefix=myproject --dry-run=False

4. Ingest subdirectories instead of parent directory:
   python -m workers.scripts.register_ondemand /path/to/data_directory --ingest-subdirs=True --dry-run=False
"""

if __name__ == "__main__":
    fire.Fire(main_register_dataset)
