{
 "title": "Node.js and Express Metrics",
 "description": "Metrics for node.js and express router status",
 "tags": [
  "node.js",
  "express",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, le)"
    }
   },
   {
    "name": "tolerated",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket, le)"
    }
   },
   { "name": "restarts_interval", "query": "1d,7d,14d,30d" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NodeJS Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Apdex Score: target $target s, tolerated $tolerated s",
   "type": "stat",
   "description": "The [Apdex score](https://en.wikipedia.org/wiki/Apdex) is the number of satisfied requests plus half of the tolerating requests plus none of the frustrated requests, divided by all the requests",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n        (   \n                sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",status_code=~\"2..\"})\n                + (\n                        sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$tolerated\",status_code=~\"2..\"})\n                        - sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",status_code=~\"2..\"})\n                ) / 2\n        ) / sum(http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"2..\"})\n) * 100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "description": "Average Requests per Second in the selected time range",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "description": "95% of requests are completed in less time than this.",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Number of requests in the selected time range",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_request_duration_seconds_count{instance=~\"$instance\"}[$__range])))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\tsum(increase(http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"[4]..\"}[$__range])OR on() vector(0))\n\t/ \n\tsum(increase(http_request_duration_seconds_count{instance=~\"$instance\"}[$__range]))\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\tsum(increase(http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"[5]..\"}[$__range])OR on() vector(0))\n\t/ \n\tsum(increase(http_request_duration_seconds_count{instance=~\"$instance\"}[$__range]))\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Restarts in $restarts_interval",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[$restarts_interval]))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of worker processes in cluster mode",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Rate of requests grouped by status (2xx, 3xx, 4xx, 5xx) over a $interval window.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\"}[$interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Status Codes Breakdown",
   "type": "piechart",
   "description": "distribution of HTTP response status codes (e.g., 2XX, 4XX, 5XX)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n    sum(increase(http_request_duration_seconds_count{instance=~\"$instance\"}[$__range])) by (status_code)\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Apdex Score: target $target s, tolerated $tolerated s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n(\n  sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=~\"2..\",le=\"$target\"}[$interval]))\n  +\n  (\n    sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=~\"2..\",le=\"$tolerated\"}[$interval]))\n    -\n    sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=~\"2..\",le=\"$target\"}[$interval]))\n  )/2\n)\n/\nsum(rate(http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"2..\"}[$interval]))\n)*100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "Top 5 Success Count",
   "type": "table",
   "description": "Number of requests in the selected time range",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, \n    round(\n        increase(\n            http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"[23]..\"}[$__range]\n        )\n    )\n)",
     "legendFormat": "{{status_code}}  {{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Count",
   "type": "table",
   "description": "Number of requests in the selected time range",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, \n    round(\n        increase(\n            http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"[45]..\"}[$__range]\n        )\n    )\n)",
     "legendFormat": "{{status_code}}  {{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, \n\n        avg by (path)(rate(http_request_duration_seconds_sum{instance=~\"$instance\", status_code=~\"[23]xx\"}[${interval}])) \n        / \n        avg by (path)(rate(http_request_duration_seconds_count{instance=~\"$instance\", status_code=~\"[23]xx\"}[${interval}]))\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Average duration of HTTP requests across all endpoints",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{instance=~\"$instance\"}[${interval}])) / avg(rate(http_request_duration_seconds_count{instance=~\"$instance\"}[${interval}]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Success Latency Buckets",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.003\"}[$__range])\n)",
     "legendFormat": "0-0.003"
    },
    {
     "expr": "sum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.03\"}[$__range])\n)\n-\nsum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.003\"}[$__range])\n)",
     "legendFormat": "0.003-0.03"
    },
    {
     "expr": "sum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.1\"}[$__range])\n)\n-\nsum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.03\"}[$__range])\n)",
     "legendFormat": "0.03-0.1"
    },
    {
     "expr": "sum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.3\"}[$__range])\n)\n-\nsum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.1\"}[$__range])\n)",
     "legendFormat": "0.1-0.3"
    },
    {
     "expr": "sum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"1.5\"}[$__range])\n)\n-\nsum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"0.3\"}[$__range])\n)",
     "legendFormat": "0.3-1.5"
    },
    {
     "expr": "sum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"10\"}[$__range])\n)\n-\nsum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"1.5\"}[$__range])\n)",
     "legendFormat": "1.5-10"
    },
    {
     "expr": "sum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"+Inf\"}[$__range])\n)\n-\nsum (\n    increase(http_request_duration_seconds_bucket{instance=~\"$instance\",status_code=\"2xx\",le=\"10\"}[$__range])\n)",
     "legendFormat": "10-Inf"
    }
   ]
  },
  {
   "title": "Node.js Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of CPU Time Spent",
   "type": "timeseries",
   "description": "CPU time used by application for every 1 second that has passed during the last $interval",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "description": "RAM usage excluding SWAP",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "virtual memory"
    },
    {
     "expr": "process_heap_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap memory"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "timeseries",
   "description": "Time between scheduling a timer and its callback being evaluated.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{instance=~\"$instance\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "nodejs_eventloop_lag_p90_seconds{instance=~\"$instance\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{instance=~\"$instance\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests/Resources",
   "type": "timeseries",
   "description": "Number of active resources that are currently keeping the event loop alive. TTYWrap, PipeWrap, TCPServerWrap, TCPSocketWrap, Immediate",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request"
    },
    {
     "expr": "nodejs_active_resources_total{instance=~\"$instance\"}",
     "legendFormat": "Active Resources"
    }
   ]
  },
  {
   "title": "Node.js Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate of Garbage Collection Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Rate of Garbage Collection",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_count{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Garbage Collection Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Garbage Collection Count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_gc_duration_seconds_count{instance=~\"$instance\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "total"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "used"
      },
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "resident"
      },
      {
       "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "external"
      }
     ]
    },
    {
     "title": "Heap Space Used",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{space}}"
      }
     ]
    }
   ]
  }
 ]
}