/**
 * The human-readable decision table the reference model produces.
 *
 * One row per distinct combination of resource type, standing, and state, listing the actions
 * the reference allows. Standing is the set of path kinds, with a grant path named by its
 * access type. State is whether a restriction or a deletion reaches the resource. A table of
 * one row per cell would be tens of thousands of rows nobody reads; collapsing equal standings
 * is what makes it reviewable.
 *
 * @see docs/design/groups/access-model-verification-plan.md — Worlds
 */

const { createReference } = require('./reference');
const W = require('./worlds');

const RESOURCE_TYPES = ['dataset', 'collection', 'group'];

/** The labels one path contributes. A member path gated by a rule contributes the rule too. */
function pathLabels(p) {
  if (p.kind === 'grant' && p.accessType) return [`grant(${p.accessType})`];
  if (p.kind === 'resource_rule') return [`rule(${p.rule})`];
  if (p.kind === 'member') {
    const member = p.direct ? 'member' : 'member(transitive)';
    return p.rule ? [member, `rule(${p.rule})`] : [member];
  }
  return [p.kind];
}

/** The reference outcome of one cell over every modelled resource type, as a string. */
function outcomeSignature(tables, cell) {
  const { world, fragments } = W.buildWorld([cell]);
  const ref = createReference(tables, world);
  const f = fragments[0];
  const ids = { dataset: f.dataset.id, collection: f.collection.id, group: f.owner.id };
  return RESOURCE_TYPES.map((resourceType) => Object.keys(tables.actions[resourceType])
    .map((a) => (ref.decide(f.user.id, resourceType, a, ids[resourceType]).allowed ? 1 : 0)).join('')).join('|');
}

/**
 * @param {Object} tables - from `modelTablesFrom`
 * @returns {{ markdown: string, cells: number, rows: number }}
 */
function renderDecisionTable(tables) {
  const cover = W.allPairs();
  const { cells } = W.addSensitivityPairs(cover, (cell) => outcomeSignature(tables, cell));
  const { world, fragments } = W.buildWorld(cells);
  const ref = createReference(tables, world);

  const rows = new Map();
  fragments.forEach((f) => {
    const ids = { dataset: f.dataset.id, collection: f.collection.id, group: f.owner.id };
    RESOURCE_TYPES.forEach((resourceType) => {
      const actions = Object.keys(tables.actions[resourceType]);
      const decisions = actions.map((a) => [a, ref.decide(f.user.id, resourceType, a, ids[resourceType])]);
      // `always` is a rule every caller satisfies, so it says nothing about standing.
      const standing = [...new Set(decisions.flatMap(([, d]) => d.paths
        .filter((p) => p.kind !== 'always')
        .flatMap(pathLabels)))].sort();
      const blocked = [...new Set(decisions.map(([, d]) => d.blockedBy).filter(Boolean))].sort();
      const allowed = decisions.filter(([, d]) => d.allowed).map(([a]) => a).sort();
      const key = `${resourceType}|${standing.join(' + ') || '(none)'}|${blocked.join(',') || '-'}`;
      // Two cells with the same standing and state must allow the same actions. If they do not,
      // the standing leaves out something the decision reads, and the table would mislead.
      const seen = rows.get(key);
      if (seen && seen.join() !== allowed.join()) {
        throw new Error(`decision table: cells ${seen.cell} and ${f.index} share "${key}" but differ`);
      }
      allowed.cell = f.index;
      rows.set(key, allowed);
    });
  });

  const lines = [
    '# Access decisions',
    '',
    'Generated by `npm run model:table` from the reference model in `api/tests/model`. Do not edit.',
    '',
    'Each row is one standing a caller can hold on one resource type, the restriction or deletion',
    'that reaches the resource, and every action the reference model allows. Standing lists every',
    'path the caller holds for any action on the resource, leaving out the `always` rule.',
    '',
    `Cells evaluated: ${cells.length}. Distinct rows: ${rows.size}.`,
    '',
    '| Resource | Standing | Blocked by | Allowed actions |',
    '|---|---|---|---|',
  ];
  [...rows.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .forEach(([key, allowed]) => {
      const [resourceType, standing, blocked] = key.split('|');
      lines.push(`| ${resourceType} | ${standing} | ${blocked} | ${allowed.join(', ') || '(none)'} |`);
    });
  lines.push('');
  return { markdown: lines.join('\n'), cells: cells.length, rows: rows.size };
}

module.exports = { renderDecisionTable, outcomeSignature, RESOURCE_TYPES };
