UPLOAD_RETRY_THRESHOLD_HOURS = 72
MAX_RETRY_COUNT = 3

UPLOAD_STATUS = {
    'UPLOADING': 'UPLOADING',
    'UPLOAD_FAILED': 'UPLOAD_FAILED',
    'UPLOADED': 'UPLOADED',
    'VERIFYING': 'VERIFYING',
    'VERIFIED': 'VERIFIED',
    'VERIFICATION_FAILED': 'VERIFICATION_FAILED',
    'PROCESSING': 'PROCESSING',
    'PROCESSING_FAILED': 'PROCESSING_FAILED',
    'COMPLETE': 'COMPLETE',
    'PERMANENTLY_FAILED': 'PERMANENTLY_FAILED',
}
