UPLOAD_RETRY_THRESHOLD_HOURS = 72

UPLOAD_STATUS = {
    'UPLOADING': 'UPLOADING',
    'UPLOAD_FAILED': 'UPLOAD_FAILED',
    'UPLOADED': 'UPLOADED',
    'PROCESSING': 'PROCESSING',
    'PROCESSING_FAILED': 'PROCESSING_FAILED',
    'COMPLETE': 'COMPLETE',
    'FAILED': 'FAILED'
}
