const argumentData = [
  {
    name: '--no-lane-splitting',
    value_type: 'BOOLEAN',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: true,
    description: 'Do not split lanes into separate files',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to all programs
  },
  {
    name: '--ignore-missing-bcls',
    value_type: 'BOOLEAN',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: true,
    description: 'Ignore missing bcls',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to bcl2fastq only
  },
  {
    name: '--ignore-missing-filter',
    value_type: 'BOOLEAN',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: true,
    description: 'Ignore missing filter',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to all programs
  },
  {
    name: '--ignore-missing-positions',
    value_type: 'BOOLEAN',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: true,
    description: 'Ignore missing positions',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to all programs
  },
  {
    name: '--delete-undetermined',
    value_type: 'BOOLEAN',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: true,
    description: 'Delete undetermined reads',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to all programs
  },
  {
    name: '--filter-single-index',
    value_type: 'BOOLEAN',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: true,
    description: 'Filter single index reads',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to all programs
  },
  {
    name: '--barcode-mismatches',
    value_type: 'NUMBER',
    allowed_values: ['0', '1', '2'],
    is_required: false,
    default_value: null,
    is_flag: false,
    description: 'Number of mismatches allowed for barcode',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to bcl2fastq only
  },
  {
    name: '--uses-bases-mask',
    value_type: 'BOOLEAN',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: true,
    description: 'Uses bases mask',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to bcl2fastq only
  },
  {
    name: '--sample-sheet',
    value_type: 'STRING',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: false,
    description: 'Sample sheet',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: 1000,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to bcl2fastq only
  },
];

module.exports = {
  argumentData,
};
