// todo - link author
// todo - link program

const conversionDefinitions = [
  {
    name: 'bcl2fastq',
    description: 'Convert BCL files to FASTQ format for Illumina sequencing data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/bcl2fastq/logs',
    output_directory: '/opt/sca/data/conversion/bcl2fastq/output',
  },
  {
    name: 'bcl-convert',
    description: 'Convert BCL files to FASTQ format for Illumina sequencing data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/bcl-convert/logs',
    output_directory: '/opt/sca/data/conversion/bcl-convert/output',
  },
  {
    name: 'cellranger-v8.0.1',
    description: 'Single-cell RNA sequencing analysis pipeline for 10x Genomics data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/cellranger-v8.0.1/logs',
    output_directory: '/opt/sca/data/conversion/cellranger-v8.0.1/output',
  },
  {
    name: 'cellranger-v6.1.2',
    description: 'Single-cell RNA sequencing analysis pipeline for 10x Genomics data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/cellranger-v6.1.2/logs',
    output_directory: '/opt/sca/data/conversion/cellranger-v6.1.2/output',
  },
  {
    name: 'cellranger-v4.0.0',
    description: 'Single-cell RNA sequencing analysis pipeline for 10x Genomics data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/cellranger-v4.0.0/logs',
    output_directory: '/opt/sca/data/conversion/cellranger-v4.0.0/output',
  },
  {
    name: 'cellranger-arc',
    description: 'Single-cell multiome analysis pipeline for RNA+ATAC sequencing data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/cellranger-arc/logs',
    output_directory: '/opt/sca/data/conversion/cellranger-arc/output',
  },
  {
    name: 'cellranger-arc-v2',
    description: 'Single-cell multiome analysis pipeline for RNA+ATAC sequencing data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/cellranger-arc-v2/logs',
    output_directory: '/opt/sca/data/conversion/cellranger-arc-v2/output',
  },
  {
    name: 'cellranger-atac',
    description: 'Single-cell ATAC-seq analysis pipeline for chromatin accessibility data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/cellranger-atac/logs',
    output_directory: '/opt/sca/data/conversion/cellranger-atac/output',
  },
  {
    name: 'spaceranger-v3.0.1',
    description: 'Spatial transcriptomics analysis pipeline for tissue imaging data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/spaceranger-v3.0.1/logs',
    output_directory: '/opt/sca/data/conversion/spaceranger-v3.0.1/output',
  },
  {
    name: 'spaceranger-v1.3.1',
    description: 'Spatial transcriptomics analysis pipeline for tissue imaging data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/spaceranger-v1.3.1/logs',
    output_directory: '/opt/sca/data/conversion/spaceranger-v1.3.1/output',
  },
  {
    name: 'spaceranger-v1.1.0',
    description: 'Spatial transcriptomics analysis pipeline for tissue imaging data',
    enabled: true,
    dataset_types: ['RAW_DATA'],
    tags: [],
    capture_logs: true,
    logs_directory: '/opt/sca/data/conversion/spaceranger-v1.1.0/logs',
    output_directory: '/opt/sca/data/conversion/spaceranger-v1.1.0/output',
  },
];

module.exports = {
  conversionDefinitions,
};
