/*
  Warnings:

  - The values [NO_MISSING_FILES] on the enum `DATASET_INGESTION_CHECK_TYPE` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "DATASET_INGESTION_CHECK_TYPE_new" AS ENUM ('FILE_COUNT', 'CHECKSUMS_MATCH', 'FILES_MISSING_FROM_DUPLICATE', 'FILES_MISSING_FROM_ORIGINAL');
ALTER TABLE "dataset_ingestion_check" ALTER COLUMN "type" TYPE "DATASET_INGESTION_CHECK_TYPE_new" USING ("type"::text::"DATASET_INGESTION_CHECK_TYPE_new");
ALTER TYPE "DATASET_INGESTION_CHECK_TYPE" RENAME TO "DATASET_INGESTION_CHECK_TYPE_old";
ALTER TYPE "DATASET_INGESTION_CHECK_TYPE_new" RENAME TO "DATASET_INGESTION_CHECK_TYPE";
DROP TYPE "DATASET_INGESTION_CHECK_TYPE_old";
COMMIT;
