const swaggerAutogen = require('swagger-autogen')();
const config = require('config');
const path = require('node:path');

const doc = {
  info: {
    title: 'API',
    description: 'Auto generated by the <b>swagger-autogen</b> module.',
  },
  host: `${config.get('express.host')}:${config.get('express.port')}`,
  schemes: ['http'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    BearerAuth: {
      type: 'apiKey',
      name: 'Authorization',
      in: 'header',
      description: 'JWT bearer token',
    },
  },
  security: [
    {
      BearerAuth: [],
    },
  ],
};

const outputFile = path.join(global.__basedir, 'swagger_output.json'); // '../../swagger_output.json';
const endpointsFiles = [path.join(global.__basedir, 'src', 'routes', 'index.js')]; // ['../routes/index.js'];

// Generate swagger.json file
function generate() {
  return swaggerAutogen(outputFile, endpointsFiles, doc);
}

if (require.main === module) {
  generate();
}

module.exports = { generate, outputFile };
