apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Ensure this matches your Prometheus container name in docker-compose
    isDefault: true
