global:
  scrape_interval: 60s  # Adjust as needed

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
  # - job_name: "api"
  #   metrics_path: "/prom-metrics"
  #   static_configs:
  #     - targets: ["host.docker.internal:3030"]