// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BatchInfo: typeof import('./src/components/runs/BatchInfo.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StepProgress: typeof import('./src/components/StepProgress.vue')['default']
    Workflow: typeof import('./src/components/runs/Workflow.vue')['default']
  }
}
