/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/Edit': RouteRecordInfo<'/about/Edit', '/about/Edit', Record<never, never>, Record<never, never>>,
    '/about/Preview': RouteRecordInfo<'/about/Preview', '/about/Preview', Record<never, never>, Record<never, never>>,
    '/alerts': RouteRecordInfo<'/alerts', '/alerts', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/cil': RouteRecordInfo<'/auth/cil', '/auth/cil', Record<never, never>, Record<never, never>>,
    '/auth/google': RouteRecordInfo<'/auth/google', '/auth/google', Record<never, never>, Record<never, never>>,
    '/auth/iucas': RouteRecordInfo<'/auth/iucas', '/auth/iucas', Record<never, never>, Record<never, never>>,
    '/auth/logout': RouteRecordInfo<'/auth/logout', '/auth/logout', Record<never, never>, Record<never, never>>,
    '/auth/microsoft': RouteRecordInfo<'/auth/microsoft', '/auth/microsoft', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dataproducts/': RouteRecordInfo<'/dataproducts/', '/dataproducts', Record<never, never>, Record<never, never>>,
    '/datasets/[datasetId]/': RouteRecordInfo<'/datasets/[datasetId]/', '/datasets/:datasetId', { datasetId: ParamValue<true> }, { datasetId: ParamValue<false> }>,
    '/datasets/[datasetId]/filebrowser': RouteRecordInfo<'/datasets/[datasetId]/filebrowser', '/datasets/:datasetId/filebrowser', { datasetId: ParamValue<true> }, { datasetId: ParamValue<false> }>,
    '/datasets/import': RouteRecordInfo<'/datasets/import', '/datasets/import', Record<never, never>, Record<never, never>>,
    '/datasetUpload/': RouteRecordInfo<'/datasetUpload/', '/datasetUpload', Record<never, never>, Record<never, never>>,
    '/datasetUpload/new': RouteRecordInfo<'/datasetUpload/new', '/datasetUpload/new', Record<never, never>, Record<never, never>>,
    '/groups/': RouteRecordInfo<'/groups/', '/groups', Record<never, never>, Record<never, never>>,
    '/groups/[groupId]/': RouteRecordInfo<'/groups/[groupId]/', '/groups/:groupId', { groupId: ParamValue<true> }, { groupId: ParamValue<false> }>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[projectId]/': RouteRecordInfo<'/projects/[projectId]/', '/projects/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/datasets/[datasetId]/': RouteRecordInfo<'/projects/[projectId]/datasets/[datasetId]/', '/projects/:projectId/datasets/:datasetId', { projectId: ParamValue<true>, datasetId: ParamValue<true> }, { projectId: ParamValue<false>, datasetId: ParamValue<false> }>,
    '/projects/[projectId]/datasets/[datasetId]/filebrowser': RouteRecordInfo<'/projects/[projectId]/datasets/[datasetId]/filebrowser', '/projects/:projectId/datasets/:datasetId/filebrowser', { projectId: ParamValue<true>, datasetId: ParamValue<true> }, { projectId: ParamValue<false>, datasetId: ParamValue<false> }>,
    '/projects/new': RouteRecordInfo<'/projects/new', '/projects/new', Record<never, never>, Record<never, never>>,
    '/rawdata/': RouteRecordInfo<'/rawdata/', '/rawdata', Record<never, never>, Record<never, never>>,
    '/stats': RouteRecordInfo<'/stats', '/stats', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/workflows/': RouteRecordInfo<'/workflows/', '/workflows', Record<never, never>, Record<never, never>>,
  }
}
