-- CreateEnum
CREATE TYPE "DATASET_ACTION_ITEM_STATUS" AS ENUM ('CREATED', 'ACKNOWLEDGED', 'LOCKED', 'RESOLVED');

-- AlterTable
ALTER TABLE "dataset_action_item" ADD COLUMN     "status" "DATASET_ACTION_ITEM_STATUS" NOT NULL DEFAULT 'CREATED';
